---
title: "hw3"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, results = "hide", fig.width=8, fig.height=4)
options(scipen = 0, digits = 3)  # controls base R output
if(!require('pacman')) {install.packages('pacman')}
pacman::p_load(bestglm, glmnet, leaps, car, tidyverse, pROC, ggplot2, caret, dplyr, dlookr, skimr, Hmisc, corrplot, lubridate, ggiraphExtra, plyr) # add the packages needed
```

#upload data
```{r include=FALSE}
hz_data <- read.csv("data/cust_survey_transaction.csv")

```

#summary statistics 

```{r include=FALSE}
skim(hz_data)
```
```{r include=FALSE}
diagnose(hz_data)
```

histogram of dependent variable: recommend hertz
```{r}
histogram(hz_data$Recommend_Hertz)
```

```{r, message=FALSE, warning=FALSE, echo=FALSE}

hz_data_numeric<- hz_data  %>% select_if(is.numeric) 

hz_cor_table <- cor(hz_data_numeric, use = "complete.obs")

corrplot(hz_cor_table, type = "upper", order = "hclust", 
         tl.col = "black", tl.srt = 45)

#hz_corr_2 <- rcorr(as.matrix(hz_data_numeric))
#hz_corr_2$r
#hz_corr_2$P
names(hz_data)
```
# QUestion 1 Continuous Variable (Regression) 
```{r create dataset we want, message=FALSE, echo=FALSE, warning=FALSE, include=FALSE, eval=FALSE}
#create new variables
hz_data_new<- hz_data %>% mutate(Time=lubridate::hms(Time),#recode Time as an hour variable
                                 time_mod=am(Time),
                                 time_mod=if_else(time_mod=="TRUE", "AM", "PM"), 
                                  Res_match=if_else(`xgra_vclass_reserv`==`xgra_veh_class`, "match", "no match"), #check match for reservation vs. assigned
                                 rent_day_mod=case_when(rent_day == 1 ~ "weekend",  #recode date, assume 1, 6, 7 are weekend 
                                                        rent_day == 2 ~ "weekday", 
                                                        rent_day == 3 ~ "weekday", 
                                                        rent_day == 4 ~ "weekday", 
                                                        rent_day == 5 ~ "weekday", 
                                                        rent_day == 6 ~ "weekend" , 
                                                        rent_day == 7 ~ "weekend"), 
                                 xgra_ckin_ts=parse_date_time(xgra_ckin_ts, orders=c("%m-%d-%y-", "%m%d%y%", "%m-%d-%y %H:%M"), exact= F), #recode string to date
                                 xgra_ckot_ts=parse_date_time(xgra_ckot_ts, orders=c("%m-%d-%y-", "%m%d%y%", "%m-%d-%y %H:%M"), exact= F),
                                 xgra_ckin_ts=as.Date(xgra_ckin_ts), #recode string to date
                                 xgra_ckot_ts=as.Date(xgra_ckot_ts),
                                 res_length=xgra_ckin_ts-xgra_ckot_ts,
                                 res_length=as.integer(res_length),#recode to integer
                                 res_length=res_length+.01, 
                                 charge_per_day=Total_charge_USD/res_length, 
                                 quarter=quarter(xgra_ckot_ts, with_year=FALSE),
                                 location_mod=if_else(addr_country=="US", "US", "Not US")) %>% 
                                 select(-Time)#calculate charge per day
#refactor variables                 
hz_data_new<- hz_data_new %>% mutate(Survey_Type=as.factor(Survey_Type), 
                                     Purpose_of_Rental=as.factor(Purpose_of_Rental),
                                     xgra_vclass_reserv=as.factor(xgra_vclass_reserv),
                                     xgra_veh_class=as.factor(xgra_veh_class), 
                                     rent_corp_lic=as.factor(rent_corp_lic),
                                     rent_day=as.factor(rent_day), 
                                     booking_channel_code=as.factor(booking_channel_code),
                                     col38_currency=as.factor(col38_currency),
                                     rent_loc_type=case_when(
                                                        rent_loc_type  =="AP" ~ "AP", 
                                                        rent_loc_type =="OFF AP" ~ "OFF AP", 
                                                        rent_loc_type =="" ~"Other"), 
                                     rent_loc_type=as.factor(rent_loc_type),
                                    cust_tier_code=as.factor(cust_tier_code),
                                    time_mod=as.factor(time_mod), 
                                    addr_st_prov=as.factor(addr_st_prov),
                                    addr_country=as.factor(addr_country), 
                                    rent_day_mod=as.factor(rent_day_mod),
                                    quarter=as.factor(quarter),
                                    rent_area_loc=as.factor(rent_area_loc),
                                    location_mod=as.factor(location_mod), 
                                    ga_region_desc=as.factor(ga_region_desc), 
                                    Res_match=as.factor(Res_match))
#Remove unnecessary variables
hz_data_sub <- hz_data_new %>% select(-xgra_n1clb_nbr, 
                                      -Hertz_Rental_Number, 
                                      -Date_of_Survey, 
                                      -Day_of_Week_survey, 
                                      -Survey_Type, 
                                      -Area, 
                                      -loc_nm, 
                                      -xgra_ckot_ts,
                                      -xgra_ckin_ts, 
                                      -xgra_vclass_reserv, 
                                      -xgra_veh_class, 
                                      -rent_alpha_code, 
                                      -rent_csr,
                                      -rent_day, 
                                      -booking_channel_code, 
                                      -Total_charges,
                                      -reserve_date, 
                                      -col38_currency,
                                      -addr_country, 
                                      -rent_area_loc, #dropped because too specific %>% 
                                      -addr_st_prov, # dropped beacuse too speicif,c rent corp lic threw singularities
                                      -rent_corp_lic) %>%  
                                      drop_na() 

summary(hz_data_sub)
write_csv(hz_data_sub, "data/clean_data.csv")
saveRDS(hz_data_sub, file="data/hz_data_sub.rds")
```


```{r split data, echo=FALSE, message=FALSE, warning=FALSE}
hz_data_sub<-readRDS("data/hz_data_sub.rds")
#select test data
set.seed(1215)
N<-length(hz_data_sub$Recommend_Hertz)
  n1<-floor(.7*N)
  n2<-floor(.3*N)
idx_train<-sample(N,n1)
idx_val<-(which(! seq (1:N) %in% idx_train))
data.train<-hz_data_sub[idx_train,]
data.val<-hz_data_sub[idx_val,]
dim(hz_data)
dim(hz_data_sub)
dim(data.train)
dim(data.val)
```

```{r full regrression, message=FALSE, echo=FALSE, warning=FALSE}
lm.full<-lm(Recommend_Hertz~., data= data.train)
  Anova(lm.full)
  summary(lm.full)
```
```{r reduced full regression, message=FALSE, echo= FALSE, message=FALSE}
vif(lm.full) # remove GA Region Desc 

#remove res_match because we need to account for quarter for seasonality, and res_match is next highest 
data.train2<-data.train %>% select(-ga_region_desc, -Res_match, -time_mod, -rent_day_mod, -charge_per_day, -rent_loc_type, -rent_cdp)
lm.small<-lm(Recommend_Hertz~., data=data.train2)
  vif(lm.small)
  Anova(lm.small) #remove time_mod
  summary(lm.small)
```


```{r LASSO regression, message=FALSE, echo=FALSE, warning=FALSE}
dim(data.train)
# extract y
data.train<-data.train %>% relocate(Recommend_Hertz,.after=last_col())
Y<-as.matrix(data.train[,21])

#extract predictors
X<-model.matrix(Recommend_Hertz~., data=data.train)[,-1]

#use LASSO
set.seed(12)

fit.fl.cv<-cv.glmnet(X, Y, alpha=1, nfolds=10, intercept=T) 
plot(fit.fl.cv)
  coef.use<-coef(fit.fl.cv, s="lambda.1se") # change if needed 
  coef.use<-coef.use[which(coef.use !=0),]
  var.min<-rownames(as.matrix(coef.use))[-1]
var.min

```




```{r relax lasso, message=FALSE, echo=FALSE, warning=FALSE}
data.train.rl<-data.train[,c("Recommend_Hertz", var.min)]
fit.relax<-lm(Recommend_Hertz~., data=data.train.rl)
    summary(fit.relax)
    Anova(fit.relax) 
    vif(fit.relax)
```

```{r compare training models linear, message=FALSE, echo=FALSE, warning=FALSE}
summary(lm.full)
summary(lm.small)
summary(fit.relax)
```


```{r compare linear models, message=FALSE, echo=FALSE, warning=FALSE, results='asis'}
p_load(stargazer)
stargazer::stargazer(fit.relax, lm.small, lm.full, title="Comparing Linear Regression Models in Training Data", type="html", column.labels=c("Lasso", "Backward Selection", "All"))
```


```{r apply final model to validation data, messagage=FALSE, warning=FALSE, echo=FALSE}
#data train
lasso<-predict(fit.relax, data.train)
  lasso.rmse<-RMSE(lasso, data.train$Recommend_Hertz)
full<-predict(lm.full, data.train)
  full.rmse<-RMSE(full, data.train$Recommend_Hertz)
reduced<-predict(lm.full, data.train)
  reduced.rmse<-RMSE(reduced, data.train$Recommend_Hertz)
compare<-data.frame(full.rmse, reduced.rmse, lasso.rmse)
  rownames(compare)<-"train"
#data validate
lasso2<-predict(fit.relax, data.val)
  lasso.rmse2<-RMSE(lasso2, data.val$Recommend_Hertz)
full2<-predict(lm.full, data.val)
  full.rmse2<-RMSE(full2, data.val$Recommend_Hertz)
reduced2<-predict(lm.full, data.val)
  reduced.rmse2<-RMSE(reduced2, data.val$Recommend_Hertz)
compare2<-data.frame(full.rmse2, reduced.rmse2, lasso.rmse2)
  colnames(compare2)<-c("full.rmse", "reduced.rmse", "lasso.rmse")
  rownames(compare2)<-"validation"
  
compare<-rbind(compare, compare2)
compare
```
```{r final model, message=FALSE, echo=FALSE, message=FALSE}

lm.final<-fit.relax

summary(lm.final)
Anova(lm.final)
vif(lm.final)
plot(lm.final)


```

#Segment EDA
```{r}

#Create tier variable 
data.train <- data.train %>% mutate(
  tier=if_else(cust_tier_code=="RG", "Basic", "Basic+"), 
)

```

#Segments 
```{r}

#Airport vs. Off-Airport
hz_data_airport <- data.train %>% filter(rent_loc_type=="AP")
hz_data_off_airport <- data.train %>% filter(rent_loc_type=="OFF AP")

summary(hz_data_airport$Recommend_Hertz)
summary(hz_data_off_airport$Recommend_Hertz)
histogram(hz_data_airport$Recommend_Hertz)
histogram(hz_data_off_airport$Recommend_Hertz)

#Business vs. Leisure vs. Loaner 
hz_data_biz <- data.train %>% filter(Purpose_of_Rental=="Business")
hz_data_personal <- data.train %>% filter(Purpose_of_Rental=="Personal")
hz_data_loan <- data.train %>% filter(Purpose_of_Rental=="Loaner")

summary(hz_data_biz$Recommend_Hertz)
summary(hz_data_personal$Recommend_Hertz)
histogram(hz_data_biz$Recommend_Hertz)
histogram(hz_data_personal$Recommend_Hertz)

#Channel 
hz_data_online <- data.train %>% filter(booking_channel_dummy==1)
hz_data_other <- data.train %>% filter(booking_channel_dummy==0)

summary(hz_data_online$Recommend_Hertz)
summary(hz_data_other$Recommend_Hertz)
histogram(hz_data_biz$Recommend_Hertz)
histogram(hz_data_personal$Recommend_Hertz)

#Customer tier
hz_data_basic <- data.train %>% filter(tier=="Basic")
hz_data_basic_plus <- data.train %>% filter(tier=="Basic+")

summary(hz_data_basic$Recommend_Hertz)
summary(hz_data_basic_plus$Recommend_Hertz)
histogram(hz_data_basic$Recommend_Hertz)
histogram(hz_data_basic_plus$Recommend_Hertz)

```


#Models with segments 
```{r}

#Airport vs. Off-Airport
model_airport <- lm(Recommend_Hertz ~ Staff_Courtesy + Speed_of_Service + Veh_Equip_Condition + Trans_Billing_as_Expected + Value_for_the_Money, data=hz_data_airport)
model_off_airport <- lm(Recommend_Hertz ~ Staff_Courtesy + Speed_of_Service + Veh_Equip_Condition + Trans_Billing_as_Expected + Value_for_the_Money, data=hz_data_off_airport)

#Business vs. Leisure vs. Loaner
model_biz <- lm(Recommend_Hertz ~ Staff_Courtesy + Speed_of_Service + Veh_Equip_Condition + Trans_Billing_as_Expected + Value_for_the_Money, data=hz_data_biz)
model_personal <- lm(Recommend_Hertz ~ Staff_Courtesy + Speed_of_Service + Veh_Equip_Condition + Trans_Billing_as_Expected + Value_for_the_Money, data=hz_data_personal)
model_loan <- lm(Recommend_Hertz ~ Staff_Courtesy + Speed_of_Service + Veh_Equip_Condition + Trans_Billing_as_Expected + Value_for_the_Money, data=hz_data_loan)

#Channel
model_online <- lm(Recommend_Hertz ~ Staff_Courtesy + Speed_of_Service + Veh_Equip_Condition + Trans_Billing_as_Expected + Value_for_the_Money, data=hz_data_online)
model_other <- lm(Recommend_Hertz ~ Staff_Courtesy + Speed_of_Service + Veh_Equip_Condition + Trans_Billing_as_Expected + Value_for_the_Money, data=hz_data_other)

#Tier
model_basic <- lm(Recommend_Hertz ~ Staff_Courtesy + Speed_of_Service + Veh_Equip_Condition + Trans_Billing_as_Expected + Value_for_the_Money, data=hz_data_basic)
model_basic_plus <- lm(Recommend_Hertz ~ Staff_Courtesy + Speed_of_Service + Veh_Equip_Condition + Trans_Billing_as_Expected + Value_for_the_Money, data=hz_data_basic_plus)

summary(model_airport)
summary(model_off_airport)
summary(model_biz)
summary(model_personal)
summary(model_loan)
summary(model_online)
summary(model_other)
summary(model_basic)
summary(model_basic_plus)

```

## Question 3
```{r, echo = FALSE}
head(data.train.rl,5)
mean(hz_data$Recommend_Hertz)
hz_data$Recommend_Hertz_binary <- if_else(hz_data$Recommend_Hertz >=mean(hz_data$Recommend_Hertz), "1", "0" )
head(hz_data,5)
set.seed(1215)
sample <- sample.int(n = nrow(hz_data), size = floor(.70*nrow(hz_data)), replace = F)
train_logit <- hz_data[sample, ]
test_logit  <- hz_data[-sample, ]
dim(train_logit)
dim(test_logit)

model_logit <- glm(Recommend_Hertz_binary ~ Staff_Courtesy + Speed_of_Service + Veh_Equip_Condition + Trans_Billing_as_Expected + Value_for_the_Money, family = "binomial", data = train_logit)
summary(model_logit)

## Out of sample hit rate

model_logit.testpred <- predict(model_logit, test_logit, type="response")

model_logit.testpred <- data.frame(model_logit.testpred)
head(model_logit.testpred,5)

fit.pred <- ifelse(model_logit.testpred$model_logit.testpred > 1/2, "1", "0")

output1 <- data.frame(test_logit$Recommend_Hertz_binary, fit.pred, model_logit.testpred$model_logit.testpred)

head(output1)
output1$test_logit.Recommend_Hertz_binary <- as.factor(output1$test_logit.Recommend_Hertz_binary)
cm_logit<- table(output1$fit.pred, output1$test_logit.Recommend_Hertz_binary)
cm_logit

## In sample hit rate
model_logit.trainpred <- predict(model_logit, train_logit, type="response")

model_logit.trainpred<- data.frame(model_logit.trainpred)
#head(model_logit.trainpred,5)

fit.pred <- ifelse(model_logit.trainpred$model_logit.trainpred > 1/2, "1", "0")

output2 <- data.frame(train_logit$Recommend_Hertz_binary, fit.pred, model_logit.trainpred$model_logit.trainpred)

head(output2)
output2$train_logit.Recommend_Hertz_binary <- as.factor(output2$train_logit.Recommend_Hertz_binary)
cm_train_logit<- table(output2$fit.pred, output2$train_logit.Recommend_Hertz_binary)
cm_train_logit

```
